---
title: "Instacart Dashboard"
output: 
  flexdashboard::flex_dashboard:
    orientation: columns
    vertical_layout: fill
---

```{r setup, include=FALSE}
library(flexdashboard)
library(tidyverse)
library(viridis)
library(p8105.datasets)

library(plotly)
```

```{r}
data("instacart")
```


```{r}
set.seed(1)

instacart = 
  instacart %>% 
  select(department, order_dow, order_hour_of_day, add_to_cart_order, aisle) %>% 
  filter(
    !is.na(order_dow),
    !is.na(order_hour_of_day)) %>% 
  sample_n(5000)
```

```{r}
common_department =
  instacart %>% 
  count(department, sort = TRUE) %>% 
  top_n(8) %>% 
  select(department)
```


Column {data-width=650}
-----------------------------------------------------------------------

### Scatter chart: Purchase time

```{r}
inner_join(instacart, common_department, by="department") %>%
  mutate(text_label = str_c("Day of week: ", order_dow, 
                            "\nHour of day: ", order_hour_of_day,
                            "\nAisle name:", aisle)) %>%
  plot_ly(x = ~order_dow, y = ~order_hour_of_day, type = "scatter", mode = "markers",
          color = ~department, text = ~text_label, colors = "Set2", alpha = 0.5)
```

Column {data-width=350}
-----------------------------------------------------------------------

### Order of select department

```{r}
inner_join(instacart, common_department, by="department") %>%
  mutate(department = fct_reorder(department, add_to_cart_order)) %>%
  plot_ly(y = ~add_to_cart_order, color = ~department, type = "box", 
          colors = "Set2")
```

### Number of purchase by department

```{r}
instacart %>% 
  count(department) %>% 
  mutate(department = fct_reorder(department, n)) %>% 
  plot_ly(x = ~department, y = ~n, color = ~department, type = "bar", 
          colors = "Set2")
```

